# Generated by Django 4.2.2 on 2023-06-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GESTION', 'Gestion'), ('VENTE', 'Vente'), ('SUPPORT', 'Support')], max_length=20),
        ),
    ]
