# Generated by Django 4.2.2 on 2023-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
