# Generated by Django 4.2.2 on 2023-06-06 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentification",
            "0006_remove_user_company_name_remove_user_mobile_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
